apiVersion: v1
kind: Template
metadata:
  name: minio-backup
parameters:
  - name: NAME_SUFFIX
    required: true
  - name: NAMESPACE
    required: true
  - name: TOOLS_NAMESPACE
    required: true
  - name: SCHEDULE
    value: "15 3 * * *"
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      finalizers:
      - kubernetes.io/pvc-protection
      name: "mongo-migrations-${NAME_SUFFIX}"
      labels:
        app: "epic-${NAME_SUFFIX}"
        name: "epic-${NAME_SUFFIX}-mongo-migrations"
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: mongo-migrations-${NAME_SUFFIX}
      namespace: "${NAMESPACE}"
    spec:
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 3
      jobTemplate:
        metadata:
          labels:
            app: "epic-${NAME_SUFFIX}"
            name: "epic-${NAME_SUFFIX}-mongo-migrations"
        spec:
          backoffLimit: 10
          template:
            spec:
              activeDeadlineSeconds: 3600
              containers:
              - image: docker-registry.default.svc:5000/${TOOLS_NAMESPACE}/mongo-migrations
                imagePullPolicy: Always
                name: mongo-migrations
                env:
                  - name: ROCKETCHAT_WEBHOOK
                    valueFrom:
                      secretKeyRef:
                        key: ROCKETCHAT_WEBHOOK
                        name: minio-rocketchat-webhook-${NAME_SUFFIX}
              restartPolicy: OnFailure
              terminationGracePeriodSeconds: 30
      schedule: ${SCHEDULE}
      successfulJobsHistoryLimit: 3
